# Copyright 2017 Schuberg Philis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: weave-net-rmpeers
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: weave-net-rmpeers
    spec:
      serviceAccount: weave-net
      containers:
      - name: rmpeers
        image: missioncriticalkubernetes/weave-net-rmpeers:1.0.1
        resources:
          requests:
            cpu: "0.01"
            memory: "20Mi"
          limits:
            cpu: "0.1"
            memory: "20Mi"
        volumeMounts:
        - name: fence
          mountPath: /unused
      hostNetwork: true
      volumes:
      - name: fence
        persistentVolumeClaim:
          claimName: weave-net-rmpeers-fence
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: weave-net-rmpeers-fence
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
